= Contributor's guide
:doc-name: CONTRIBUTORS.adoc

Contributions to the SeaLion Mission ConOps can come in a variety of roles. This document is intendend to provide guidelines for 3 types of contributors: subject-matter experts, technical writers, and developers.

== Contribute as a subject-matter expert

A subject-matter expert (SME) or domain expert is a person who is an authority in a particular area or topic.
SMEs work with technical writers to validate the content of the documentation.

SMEs can primarily contribute by link:{doc-name}#contributing-to-discussions[Contributing to discussions].

== Contribute as a technical writer

A technical writer is a person who maintains the state of the documentation. Technical writers work with users, developers, and/or SMEs in order to document the intended design and behavior of the codebase, to maintain a consistent format, style, and tone, as well as to verify the contents readablility and usability.

Technical writers can primarily contribute by link:{doc-name}#contributing-to-documentation[Contributing to documentation].

== Contribute as a developer

A developer is a person who implements the codebase, as specified by the documentation. Developers should refer to the documentation to implement and test the intended design and behavior of the software in development.

Developers can primarily contribute by both link:{doc-name}#contributing-to-documentation[Contributing to documentation] and link:./contributing-to-code[Contributing to code].

