= Contributor's guide
:doc-name: CONTRIBUTORS.adoc
:project-name: SeaLion Mission ConOps
:github-repo: https://github.com/odu-cga-cubesat/mission-conops

Contributions to the {project-name} can come in a variety of roles. This document is intendend to provide guidelines for 2 types of contributors: subject-matter experts and technical writers.

== Contribute as a subject-matter expert

A subject-matter expert (SME) or domain expert is a person who is an authority in a particular area or topic.
SMEs work with technical writers to validate the content of the documentation.

SMEs can primarily contribute by link:{doc-name}#contributing-to-discussions[Contributing to discussions].

== Contribute as a technical writer

A technical writer is a person who maintains the state of the documentation. Technical writers work with users, developers, and/or SMEs in order to document the intended design and behavior of the codebase, to maintain a consistent format, style, and tone, as well as to verify the contents readability and usability.

Technical writers can primarily contribute by link:{doc-name}#contributing-to-documentation[Contributing to documentation].

== Contributing to discussions

The {github-repo}/discussions[Discussions] and {github-repo}/issues[Issues] sections help facilitate invaluable feedback and discourse in the development and maintainability of the {project-name}

=== Opening a discussion

Discussions can include general topics, ideas, and Q&A.

To open a new discussion,

. On GitHub, navigate to the {project-name} repository and click {github-repo}/discussions[Discussions].
. Click *New discussion*.
. Select a discussion category from the drop-down menu.
. Specify a title for the discussion topic, e.g., _Alternative Mission ConOps_.
. Write a brief description of the scope of the discussion, e.g., _This discussion is for brainstorming alternative mission concept of operations_.
. Click *Start discussion*.

See https://docs.github.com/en/discussions/quickstart#creating-a-new-discussion[Creating a new discussion].

