= Contributor's guide
:doc-name: CONTRIBUTORS.adoc
:project-name: SeaLion Mission ConOps
:github-repo: https://github.com/odu-cga-cubesat/mission-conops

Contributions to the {project-name} can come in a variety of roles. This document is intendend to provide guidelines for 2 types of contributors: subject-matter experts and technical writers.

== Contribute as a subject-matter expert

A subject-matter expert (SME) or domain expert is a person who is an authority in a particular area or topic.
SMEs work with technical writers to validate the content of the documentation.

SMEs can primarily contribute by link:{doc-name}#contributing-to-discussions[Contributing to discussions].

== Contribute as a technical writer

A technical writer is a person who maintains the state of the documentation. Technical writers work with users, developers, and/or SMEs in order to document the intended design and behavior of the codebase, to maintain a consistent format, style, and tone, as well as to verify the contents readability and usability.

Technical writers can primarily contribute by link:{doc-name}#contributing-to-documentation[Contributing to documentation].

== Contributing to discussions

The {github-repo}/discussions[Discussions] and {github-repo}/issues[Issues] sections help facilitate invaluable feedback and discourse in the development and maintainability of the {project-name}

=== Opening a discussion

Discussions can include general topics, ideas, and Q&A.

To open a new discussion,

. On GitHub, navigate to the {project-name} repository and click {github-repo}/discussions[Discussions].
. Click *New discussion*.
. Select a discussion category from the drop-down menu.
. Specify a title for the discussion topic, e.g., _Alternative Mission ConOps_.
. Write a brief description of the scope of the discussion, e.g., _This discussion is for brainstorming alternative mission concept of operations_.
. Click *Start discussion*.

See https://docs.github.com/en/discussions/quickstart#creating-a-new-discussion[Creating a new discussion].

== Contributing to documentation

Contributions to documentation can include, but not limited to, creating, updating, and/or reviewing content for the {project-name}.
We use a https://www.writethedocs.org/guide/docs-as-code/[docs-as-code] approach and the https://guides.github.com/introduction/flow/[GitHub flow] workflow to fascilitate these contributions.
To decide what you can contribute, read through the list of {github-repo}/issues[Issues] and comment on the issue if you'd either like to work on the particular issue or require additional clarity on the issue.
Contributors are also welcome to link:{doc-name}#opening-an-issue[open an issue].
Once you decide which issue you'd like to work on, you can link:{doc-name}#submitting-a-pull-request[submit a pull request].

== Opening an issue

{github-repo}/issues[Issues] specify tasks that allow maintainers to capture & resolve missing or incorrect content, as well as implement new features or bug fixes in the documentation build tools.
Some issues are grouped by {github-repo}/milestones[Milestones] - a collection of issues that relate to a specific deliverable. Completed milestones are tagged as a {github-repo}/releases[Release].

To open an issue,

. On GitHub, navigate to the {project-name} repository and click {github-repo}/issues[Issues]
. Click *New issue*.
. Specify a title for the issue topic. A good issue title should start with a verb, e.g., _add CubeSat Design Specification as a reference in architecture_.
. Write a brief description of the scope of the issue, e.g., _architecture/0-References directory should include a reference for the latest CubeSat Design Specification document_.
. Click *Submit new issue*.

See https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue[Creating an issue].
