= Contributor's guide
:toc:
:toclevels: 3
:doc-name: CONTRIBUTORS.adoc
:project-name: SeaLion Mission ConOps
:github-repo: https://github.com/odu-cga-cubesat/mission-conops

Contributions to the {project-name} can come in a variety of roles. This document is intendend to provide guidelines for 2 types of contributors: subject-matter experts and technical writers.

== Contribute as a subject-matter expert

A subject-matter expert (SME) or domain expert is a person who is an authority in a particular area or topic.
SMEs work with technical writers to validate the content of the documentation.

SMEs can primarily contribute by link:{doc-name}#contributing-to-discussions[Contributing to discussions].

== Contribute as a technical writer

A technical writer is a person who maintains the state of the documentation. Technical writers work with users, developers, and/or SMEs in order to document the intended design and behavior of the codebase, to maintain a consistent format, style, and tone, as well as to verify the contents readability and usability.

Technical writers can primarily contribute by link:{doc-name}#contributing-to-documentation[Contributing to documentation].

== Contributing to discussions

The {github-repo}/discussions[Discussions] and {github-repo}/issues[Issues] sections help facilitate invaluable feedback and discourse in the development and maintainability of the {project-name}

=== Opening a discussion

Discussions can include general topics, ideas, and Q&A.

To open a new discussion,

. On GitHub, navigate to the {project-name} repository and click {github-repo}/discussions[Discussions].
. Click *New discussion*.
. Select a discussion category from the drop-down menu.
. Specify a title for the discussion topic, e.g., _Alternative Mission ConOps_.
. Write a brief description of the scope of the discussion, e.g., _This discussion is for brainstorming alternative mission concept of operations_.
. Click *Start discussion*.

See https://docs.github.com/en/discussions/quickstart#creating-a-new-discussion[Creating a new discussion].

== Contributing to documentation

Contributions to documentation can include, but not limited to, creating, updating, and/or reviewing content for the {project-name}.
We use a https://www.writethedocs.org/guide/docs-as-code/[docs-as-code] approach and the https://guides.github.com/introduction/flow/[GitHub flow] workflow to fascilitate these contributions.
To decide what you can contribute, read through the list of {github-repo}/issues[Issues] and comment on the issue if you'd either like to work on the particular issue or require additional clarity on the issue.
Once you decide which issue you'd like to work on, you can link:{doc-name}#submitting-a-pull-request[submit a pull request].
Contributors are also welcome to link:{doc-name}#opening-an-issue[open an issue] as well as help with link:MAINTAINERS.adoc#reviewing-a-pull-request[reviewing a pull request].

== Opening an issue

{github-repo}/issues[Issues] specify tasks that allow maintainers to capture & resolve missing or incorrect content, as well as implement new features or bug fixes in the documentation build tools.
Some issues are grouped by {github-repo}/milestones[Milestones] - a collection of issues that relate to a specific deliverable. Completed milestones are tagged as a {github-repo}/releases[Release].

To open an issue,

. On GitHub, navigate to the {project-name} repository and click {github-repo}/issues[Issues]
. Click *New issue*.
. Specify a title for the issue topic. A good issue title should start with a verb, e.g., _add CubeSat Design Specification as a reference in architecture_.
. Write a brief description of the scope of the issue, e.g., _architecture/0-References directory should include a reference for the latest CubeSat Design Specification document_.
. Click *Submit new issue*.

See https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue[Creating an issue].

== Submitting a pull request

A https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests[pull request] is a proposal for changes to a https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches[branch].

To submit a pull request,

. https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository#creating-a-branch[Create a new branch] in the link:{github-repo}[{project-name}] repo.
The branch name should be prepended with its associated issue label followed by a `/`, followed by a `dash-separated` description of the changes to be made, followed by its associated issue number, e.g., `feature/add-tricoder-with-touchscreen-docs-1701`. If no such issue exists, link:{doc-name}#opening-an-issue[open an issue]. NOTE: If you haven't been added as a collaborator to the link:{github-repo}[{project-name}] repo, you will need to either https://docs.github.com/en/get-started/quickstart/fork-a-repo[fork] the repo or contact the repo admin to request write access.
. As you edit your content, ensure that it conforms to the link:{doc-name}#content-style-guide[content style guide].
. Commit your changes and https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request[create a pull request]. Be sure to include a https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords[closing keyword] followed by the associated issue number in the pull request description, e.g., `closes #1701`. If the pull request closes multiple issues, add a closing keyword for each issue. NOTE: If you are creating a pull request from a forked repo, be sure that the https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request[base branch] of the pull request is set the `main` branch of the link:{github-repo}[{project-name}] repo, not your forked repo.
. If you're not yet ready for a review, mark the pull request as _Draft_ to indicate it's a work in progress. Continue updating your doc and pushing your changes until you're happy with the content.
. When you're ready for a review, mark the pull request as _Ready for review_.
. Once your pull request has been merged, you can safely delete your branch.

== Content style guide

=== Architecture

Yaml files in `architecture/` should subside in `0-References/`, `1-StakeholderNeeds`, or `2-UserStories`, `3-Datastructures` and be prependend with a number, followed by a dash and the content name in https://wiki.c2.com/?PascalCase[Pascal Case]. e.g., `2-CubeSatDesignSpecificationRev13.yml` 

=== Components

`package.json` files for components in the `components` directory (and subdirectories) should conform to the specification for a https://mach30.github.io/dof/#_component[DOF-Component].

== Semantic versioning

We use semantic versioning (https://semver.org/[semver]) for denoting changes/updates to the {project-name} under `version` in the link:{github-repo}/package.json[package.json]. Given the version number *MAJOR*.*MINOR*.*PATCH*, increment the:

. *MAJOR* version when you make incompatible API changes.
e.g., removing or renaming a file or folder in the `architecture/` or `components/` directory
. *MINOR* version when you add functionality in a backwards compatible manner.
e.g., adding a file or folder in the `architecture/` or `components/` directory, and
. *PATCH* version when you make backwards compatible bug fixes.
e.g., updating the contents of a file in the `architecture/` or `components/` directory

