@startuml

state AntennaDeployment
      AntennaDeployment : Turn on current supply to antenna burnwire mechanism for 1 minute
      AntennaDeployment : Record deployment time to event log
state SafeHold
      SafeHold : Transmit SeaLion Beacon
state QueryReceiver
      QueryReceiver : Listen for ground station command for next 2 minutes
state TelemetrySender
      TelemetrySender : Downlink requested telemetry packet
state EventLogSender
      EventLogSender : Downlink requested event log
state Timer
      Timer : Compute delta_time_beacon
      Timer : Compute delta_time_GPS
state MissionMode1
      MissionMode1 : Record impedence probe data to event log for next 2 minutes at 1 second intervals
state MissionMode2
      MissionMode2 : Turn on current supply to DeCs burnwire mechanism for 1 minute
      MissionMode2 : Record DeCS strain gauge data to event log for next 2 minutes at 1 second intervals
state MissionMode3
      MissionMode3 : Record multi-spectral sensor data to event log for next 2 minutes at 1 second intervals
state ProcessDispatcher
      ProcessDispatcher : Check runqueue for scheduled task
state OrbitPropagator
      OrbitPropagator : Generate orbit propagation table
state BeaconScheduler
      BeaconScheduler : Schedule a beacon to occur on estimated upcoming ground station overpass
state GPSreceiver
      GPSreceiver : Ping GPS
state QueryHandler
      QueryHandler : Process query from ground station
state ProcessScheduler
      ProcessScheduler : Add scheduled task to runqueue

[*] --> AntennaDeployment : Power on EPS & CDS \n Wait 45 mins
AntennaDeployment --> SafeHold
SafeHold --> QueryReceiver
QueryReceiver --> QueryHandler : Ground station command received
QueryReceiver --> Timer : No ground station command
QueryHandler --> TelemetrySender : Telemetry requested
QueryHandler --> EventLogSender : Event log requested
QueryHandler --> ProcessScheduler : Task scheduling requested
TelemetrySender --> QueryReceiver
EventLogSender --> QueryReceiver
ProcessScheduler --> QueryReceiver
MissionMode1 --> Timer
MissionMode2 --> Timer
MissionMode3 --> Timer
GPSreceiver --> OrbitPropagator
OrbitPropagator --> BeaconScheduler
BeaconScheduler --> ProcessDispatcher
Timer --> SafeHold : if delta_time_beacon >= 30 mins
Timer --> GPSreceiver : elseif delta_time_GPS >= 2 mins
Timer --> ProcessDispatcher : else
ProcessDispatcher --> MissionMode1 : scheduled for MM1
ProcessDispatcher --> MissionMode2 : scheduled for MM2
ProcessDispatcher --> MissionMode3 : scheduled for MM3
ProcessDispatcher --> Timer : empty runqueue
ProcessDispatcher --> EventLogSender : scheduled event log downlink
ProcessDispatcher --> TelemetrySender : scheduled telemetry downlink
ProcessDispatcher --> SafeHold : scheduled telemetry beacon
@enduml
