= Flight Software Systems Architecture for the Sealion Mission
:presentation_title: Flight Software Systems Architecture for the Sealion Mission

v5.0.0

by Robert Borowicz, Patrick Clark, Kevin Chiu, Gonzalo Fernandez Mediavilla, Bhagatji Jimesh, Sean Marquez, Payal Nandi, Joseph Siciliano, & Gus Williams

== Homepage

https://ODU-CGA-CubeSat.github.io/sealion-mission-architecture

== Design Philosophy

The {presentation_title} follows a https://www.writethedocs.org/guide/docs-as-code/[docs-as-code] & https://www.writethedocs.org/videos/portland/2019/lessons-learned-in-a-year-of-docs-driven-development-jessica-parsons/[docs-driven development] approach, as to ensure:

* Documentation and development are tightly coupled.
* No requirement or feature goes undocumented.

== Stakeholder Needs
 
The {presentation_title} is guided by a series of stakeholder needs...

[plantuml, stakeholder-needs-mapping, svg]
....
include::./stakeholder-needs-mapping.puml[Stakeholder Needs Mapping]
....

== User Stories

The {presentation_title}'s stakeholder needs are then used to identify a series of user stories which then lead to design decisions captured in data structure and activity definitions.

[plantuml, user-stories-mapping, svg]
....
include::./user-stories-mapping.puml[User Stories Mapping]
....


=== User stories as Use Case Diagram

[plantuml, use-case-diagram, svg]
....
include::./use-case-diagram.puml[User Stories as Use Case Diagram]
....

== Data Structures
This section covers each data structure type in the *{presentation_title}*.

[plantuml, data-structures-mapping, svg]
....
include::./data-structures-mapping.puml[Data Structures Mapping]
....

== Finite State Machine

[plantuml, fsm, svg]
....
include::./operating-mode-as-fsm.puml[Finite State Machine]
....
