= SeaLion Mission ConOps

This repository (repo) contains the source code & documentation for the SeaLion Mission Concept of Operations (ConOps) - a joint CubeSat mission between Old Dominion University (ODU) & Coast Guard Academy (CGA).

The repo contains an architecture, modeled using the Mach30 modeling language (https://github.com/Mach30/m30ml[m30ml]), for specifying references, stakeholder needs, user stories, & data structures for fascilitating traceability of design decisions within the Mission ConOps (s.a., the packet definition used for carrying telemetry data).
The repo itself is also structured as a https://mach30.github.io/dof/#_component[DOF-component] for defining the contents of the Mission ConOps as a collection of nested subcomponents, component interfaces, and component functions for generating bill of materials (BOMs), assembly instructions, and/or usage documentation.

Full documentation is available on https://odu-cga-cubesat.github.io/mission-conops/.

This project follows a https://www.writethedocs.org/guide/docs-as-code/[docs-as-code] & https://www.writethedocs.org/videos/portland/2019/lessons-learned-in-a-year-of-docs-driven-development-jessica-parsons/[docs-driven development] approach, using the https://asciidoctor.org/docs/what-is-asciidoc/[asciidoc] markup language.

== View the documentation locally

You can build the documentation site on a local desktop:

Note: It is recommended you run the following instructions on a Linux/Unix-like operating system. If you are on a Windows machine, consider installing https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux].

=== Installing requirements

You will need https://git-scm.com/[git] to clone the project contents and https://www.docker.com/[docker] to run the docker image that contains the dependencies needed for building the documentation.

. https://git-scm.com/downloads[git].
. https://docs.docker.com/get-docker/[docker].

=== Cloning the repo

Clone the https://github.com/odu-cga-cubesat/mission-conops[SeaLion Mission ConOps repo]. Don't forget to use `--recurse-submodules` flag, or else you won't pull down some of the code you need to generate a working site.

[source,bash]
----
git clone --recurse-submodules https://github.com/odu-cga-cubesat/mission-conops.git
cd mission-conops
----

Note: If you accidentally cloned without using `--recurse-submodules`, you can run `git submodule update --init --recursive` to pull down submodules needed to generate a working site.

=== Building the documentation

Once you've cloned the repo & installed docker, run the `buildDocs.sh` script in the project root directory (Note: Linux users may need to prepend this command `sudo`). This will build a docker image, as well as install node modules, needed for generating the `mission-conops` page locally. You can view all locally installed docker images by running `docker images`.

[source,bash]
----
./buildDocs.sh
----

Once you run this step, you can locally view the documentation by opening `dist/index.html` in a web browser.
