= Model-Based CubeSat Flight-Software Architecture using a Docs-as-Code approach
:bibtex-file: references.bib
:bibtex-style: ieee
:bibtex-order: appearance

== Introduction

Model-Based Systems Engineering (MBSE) is an approach to systems engineering whereby models,
as opposed to documents,
serve as the _authoritative source of truth_ for conducting systems engineering activities,
such as the design, specification, analysis, verification & validation of a sytem cite:[architecting_spacecraft].

For the SeaLion Mission, a joint CubeSat mission between the Old Dominion University and Coast Guard Academy,
the flight software team adopted an MBSE approach to flight software architecture,
using a docs-as-code approach cite:[docs_as_code],
whereby the same tools and methodologies for managing software are also used for configuration management of documentation.
Applying both an MBSE and docs-as-code approach means that aspects of the mission architecture,
such as stakeholder needs, user stories, and data structures pertaining to the CubeSat mission,
are captured are within a model that is both human-readable and machine-queryable.

This article presents the modeling language, tools, and technical approach used to fascilitate the configuration management, design, specification, & implementation of the SeaLion mission architecture for the flight software. 

== Mach30

The SeaLion Architecture uses the Mach30 modeling language (m30ml) cite:[mach30_git], to specify references, stakeholder needs, user stories, & data structures for facilitating traceability of design decisions within the Mission ConOps.  The SeaLion repository is also structured as a Distributed OSHW Framework (DOF)-component for defining the contents of the Mission ConOps as a collection of nested subcomponents, component interfaces, and component functions for generating bill of materials (BOMs), assembly instructions, and/or usage documentation.

This is all done in an effort to execute the project via a documentation as code philosophy.  A philosophy in which documentation is written with the same tools as code cite:[docs_as_code].  This allows for workflows between development teams to be more closely integrated.

== Stakeholders

The SeaLion project’s methodology documentation uses m30ml based on YAML architecture modeling tools.  The first step to build the architecture is to define the stakeholder needs.  The two stakeholders for Sealion are ODU and CGA with their respective needs categorized on priority from primary to secondary to tertiary.  These stakeholder needs are listed in the following Table 1.

.Stakeholder Needs
|===
|User Story |Description

|1.1: Primary Mission Objective A1
|The SeaLion mission shall establish UHF communication link with Virginia ground station.

|1.2: Primary Mission Objective A2
|The SeaLion mission shall establish S-Band communication link with MC3 ground station.

|1.3: Primary Mission Objective A3
|The SeaLion mission shall successfully transmit “mission data” defined above to ground stations on the Earth.

|1.4: Primary Mission Objective A4
|The SeaLion mission shall adhere to CubeSat standards as per CubeSat Design Specification (CDS) Rev. 13. cite:[cds_13]

|1.5: Primary Mission Objective A5
|The SeaLion mission shall validate the operation of the Impedance Probe (IP) as a primary payload in-orbit.

|2.1: Secondary Mission Objective B1
|The SeaLion mission shall provide a means to validate a Multi-spectral Sensor (Ms-S) in-orbit.

|2.2: Secondary Mission Objective B2
|The SeaLion mission shall provide a means to validate a deployable composite structure (DeCS) in-orbit.

|3.1: Tertiary Mission Objective C1
|The SeaLion mission shall qualify on-orbit the deployment and functioning of the newly developed UHF antenna system and its deployment.

|3.2: Tertiary Mission Objective C2
|The SeaLion mission shall qualify a CubeSat bus architecture for very-low Earth orbit (VLEO).

|3.3: Tertiary Mission Objective C3
|The SeaLion shall verify DeCS in-orbit behavior performance.
|===

== User Stories

The SeaLion Mission Architecture’s stakeholder needs are then used to identify a series of user stories which then lead to design decisions captured in data structure and activity definitions.  These are created from the perspective of the ground station operator to define the tasks that need to be completed to satisfy the user stories. 

The user story example is to view the satellite beacon data is as follows:

* User Story: As a Ground Station Operator I want to view satellite beacon data (alternating between health & mission data), received via UHF so that I can verify that satellite is operating nominally.
* Example: View satellite beacon data (health or mission data) to verify that TLE’s correspond with expected orbit profile and/or to validate that a mission mode was successful.
* Derived From:
** Primary Mission Objective A1
** Primary Mission Objective A3
** Primary Mission Objective A5
** Secondary Mission Objective B1
** Secondary Mission Objective B2
** Tertiary Mission Objective C1
** Tertiary Mission Objective C2
** Tertiary Mission Objective C3

== References

bibliography::[]

