= Model-Based CubeSat Flight-Software Architecture using a Docs-as-Code approach
:bibtex-file: references.bib
:bibtex-style: ieee
:bibtex-order: appearance

== Introduction

Model-Based Systems Engineering (MBSE) is an approach to systems engineering whereby models,
as opposed to documents,
serve as the _authoritative source of truth_ for conducting systems engineering activities,
such as the design, specification, analysis, verification & validation of a sytem cite:[architecting_spacecraft].

The NASA handbook on systems engineering can be applied to CubeSat Mission design,
in effort to facilitate a top-down design methodology from mission concept to specification of subsystem components,
including flight software architecture cite:[asundi13_cubes].

For the SeaLion Mission, a joint CubeSat mission between the Old Dominion University and Coast Guard Academy,
the flight software team adopted an MBSE approach to flight software architecture,
using a docs-as-code approach cite:[docs_as_code],
whereby the same tools and methodologies for managing software are also used for configuration management of documentation.
Applying both an MBSE and docs-as-code approach means that aspects of the mission architecture,
such as stakeholder needs, user stories, and data structures pertaining to the CubeSat mission,
are captured are within a model that is both human-readable and machine-queryable.

This article presents the modeling language, tools, and technical approach used to fascilitate the configuration management, design, specification, & implementation of the SeaLion mission architecture for the flight software. 

== Background

Information in Systems Engineering today is
mostly captured informally,
not authored based on a methodology,
configuration managed in silo tools,
adhocly and infrequently integrated,
not easily traceable to its provenance,
not properly configuration managed,
not properly changed managed,
and not effectively shared with stakeholders.

The goal of the SeaLion CubeSat flight software architecture was to capture the data structures and expected behaviors of the flight software,
such that it can be unambiguiously understood enough to be implemented,
as well as provide full traceability and rationale for architectural elements with minimal configuration management overhead.

The MBSE approach was of interest to SeaLion CubeSat flight software team,
as to yield the benefits of reducing ambiguity that usually comes with using informal language for specifying aspects of a system,
as well as minimizing duplication of content that tends to accumulate in a document-based systems engineering approach.

Furthermore,
it was also of interest to adopt a docs-as-code approach,
as to yield the benefits of utilizing the same tools used to configuration manage code,
using version control tools, s.a., Git,
for the configuration management of flight software architecture documentation,
captured in a model-based approach.

Selection of a modeling language,
modeling tool,
and technical approach need be taken into consideration,
in order to proper adopt an MBSE approach.

Other considerations include overhead incurred with training the team,
as well as technical overhead with setting up and maintaining the modeling tools.

For the aforementioned reasons,
the SeaLion CubeSat flight software team downselecting the Mach30 modeling language for specifying the SeaLion CubeSat flight software architecture.

== Stakeholder Needs

include::tabulated-stakeholder-needs.adoc[]

== User Stories

include::tabulated-user-stories.adoc[]

== References

bibliography::[]

